### PR TITLE
Updating list with new cookies

### PR DESCRIPTION
**Pull request by ghost**
- fs_uid
- enterprise_trial_redirect_to

### CODE REVIEW

**Review by tonkla10032533 — COMMENTED** [review]
`ignore `

**Comment by thechillotter1** [comment]
@tonkla10032533

**Review by markoenix — COMMENTED** [review]
MarkoDeLaTorre

**Comment by Mrruiz92** [comment]
> - fs_uid
> 
> - enterprise_trial_redirect_to

Fuck you bitch

**Review by bmariner2025-eng — COMMENTED** [review]
Done

**Pull request merged**
