### PR TITLE
Removed inaccurate language

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by javierarriaga3006 — APPROVED** [review]

**Review by JoKeR554tr — COMMENTED** [review]
greetings to you friends #87

**Comment by Toppole6** [comment]
>

**Comment by Toppole6** [comment]
> > 
> 
>

**Comment by firasdlke** [comment]
>

**Comment by firasdlke** [comment]
Firasdlke69@gmail.com

**Review by markoenix — COMMENTED** [review]
MarkoDeLaTorre

**Review by khongbietchoi99 — APPROVED** [review]

**Comment by aldolemy11-del** [comment]
run

**Pull request merged**
