### PR TITLE
Bot/cookie update 20221101

### PR DESCRIPTION
**Pull request by ghost**
Updating list with additional cookies that will be introduced on some marketing related pages

### CODE REVIEW

**Comment by Pasio47DBG** [comment]
47196096f6264acbdc6dd3173fc78f1c5b2ea9c3

**Review by Pasio47DBG — APPROVED** [review]

**Review by Pasio47DBG — APPROVED** [review]

**Comment by Qazplmqwerty** [comment]
No u cannot use this bypass

**Review by rufo1 — APPROVED** [review]

**Review by aszezo12 — COMMENTED** [review]
>

**Review by alam302883848484 — COMMENTED** [review]
Yyy

**Pull request merged**
